name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allow manual triggers

jobs:
  build-and-push:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 3: Build and push client image with build argument
      - name: Build and push client image
        run: |
          docker build --build-arg REACT_APP_API_URL=http://server:5000 -t ${{ secrets.DOCKER_USERNAME }}/client:latest ./client
          docker push ${{ secrets.DOCKER_USERNAME }}/client:latest

      # Step 4: Build and push server image
      - name: Build and push server image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/server:latest ./server
          docker push ${{ secrets.DOCKER_USERNAME }}/server:latest